### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [vayan/autosub-mpv#1]
Great script, been using it for a while now, but I'm having trouble now that I'm using Kodi to access files.

http://forum.kodi.tv/showthread.php?tid=282135

Any idea?

**Comment by vayan** [comment]
:thought_balloon: Mhh... I don't use Kodi, but do you have write access to the video folder ? 
Usually it crashes silently.. maybe there's a problem with your Python install on Windows ?

**Comment by 2V3EvG4LMJFdRe** [comment]
Yeah, I do. I feel like the problem lies in that Kodi uses Python, too, so my standalone install clashes with the one on Kodi. Do you know if it would be possible to make it run with the Kodi one?

**Comment by vayan** [comment]
Kodi is installed on the same computer where you're reading your files ? 

If yes you should try to install `subliminal` with Kodi's python and change the path in here https://github.com/vayan/autosub-mpv/blob/master/autosub.lua#L6

**Comment by 2V3EvG4LMJFdRe** [comment]
Yeah, same computer. But I'm not very good at this, and could not understand how to run it with Kodi's Python, mostly because there's no python.exe anywhere inside Kodi's folder, so I don't know how Kodi's python scripts are even running.

By the way, I'm on a new install of Windows. This time I installed Python 2 instead of 3, and now it simply doesn't work, it's an immediate subtitle download failure, bypassing the 'Python is not responding' window.

I'm gonna go ask the Subliminal guys now.

**Comment by vayan** [comment]
Cleaning up issues 😄 tell me if you want to reopen it
