### ISSUE TITLE
Download multiple subtitle and manually select one of them?

### ISSUE THREAD

**Issue by CatTail** [vayan/autosub-mpv#3]
Is that possible, is mpv gui support user interaction?

**Comment by vayan** [comment]
What for? To select other languages? subliminal is supposed to select the best subtitle it usually works quite well (https://subliminal.readthedocs.io/en/latest/user/how_it_works.html)

**Comment by CatTail** [comment]
subliminal use score algorithm to find best match for a video, however, there maybe have same score with different subtitles.

For example, multiple chinese subtitle translated from english for one video will have the same score, and user should decide which one fits.

**Comment by vayan** [comment]
Oh I see, what if I download the first X subtitles with the same score then you can use mpv built-in features to switch subtitles?

**Comment by CatTail** [comment]
That's great, Thanks!

**Comment by vayan** [comment]
Reopening this issue to remember to do it :smile:

**Comment by CatTail** [comment]
Close since this issue is not active for a long time.
