### ISSUE TITLE
Login to subtitle sites

### ISSUE THREAD

**Issue by alfablac** [vayan/autosub-mpv#5]
subliminal supports a few sites that require authentication.
How can I do this in the script.
Didn't find how to save configuration files in subliminal on Windows.

**Comment by vayan** [comment]
I didn't find any config file either 😕  

You can follow this: https://github.com/Diaoul/subliminal/issues/553

**Comment by vayan** [comment]
You could try this one https://github.com/davidde/mpv-autosub seems better than mine 👍
