### ISSUE TITLE
question (don't know where to ask)

### ISSUE THREAD

**Issue by pashosh** [vayan/autosub-mpv#6]
can i add another language to download subtitles for?
sometimes there are no subtitles in my language (hebrew) so i want it to also download english subtitles.
i changed your original script to have "he" instead "en" and it is working great but can i add also "en" to there (and how of course) to also download english subtitles?

**Comment by vayan** [comment]
You could probably do something like: 

`t = { args = { "subliminal", "download", "-s", "-f", "-l", "en", "-l", "he", path } }` 

see: https://subliminal.readthedocs.io/en/latest/user/cli.html#subliminal-download 

👍

**Comment by pashosh** [comment]
thanks.
i did it:
`  t = { args = { "subliminal", "download", "-s", "-f", "-l", "he", "-l", "en", path } }`
but it download just the english subtitles and not the hebrew (and there are hebrew subtitles for the file i check :-))

**Comment by vayan** [comment]
What version of subliminal do you have?

**Comment by pashosh** [comment]
2.0.5

**Comment by vayan** [comment]
Try this one https://github.com/davidde/mpv-autosub they support multi languages maybe it'll work
